# Generated by Django 5.2.4 on 2025-09-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(max_length=100)),
                ('vendor_id', models.IntegerField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('vendorpassword', models.CharField(max_length=100)),
                ('productbrought', models.CharField(max_length=255)),
            ],
        ),
    ]
