# Generated by Django 5.2.4 on 2025-09-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_add',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('describtion', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.IntegerField(unique=True),
        ),
    ]
