# Generated by Django 5.2.4 on 2025-09-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_product_add_alter_staff_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.IntegerField(),
        ),
    ]
