# Generated by Django 5.2.4 on 2025-09-23 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_alter_staff_staff_id_alter_vendor_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_add',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
