# Generated by Django 5.2.4 on 2025-09-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_product_add_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_product',
            fields=[
                ('vendor_id', models.CharField(max_length=100)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_brand', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('describtion', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_pwd', models.CharField(max_length=100)),
            ],
        ),
    ]
