# Generated by Django 5.2.4 on 2025-09-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_vendor_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_product',
            name='vendor_pwd',
        ),
    ]
