# Generated by Django 5.2.4 on 2025-09-25 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_remove_vendor_product_vendor_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=255)),
                ('order_quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='vendor_product',
        ),
        migrations.AddField(
            model_name='product_add',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_add',
            name='vendor_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_add',
            name='vendor_product_brand',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
