# Generated by Django 5.2.4 on 2025-09-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_addcart_user_delete_vendor_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_add',
            name='vendor_product_brand',
            field=models.CharField(default='', max_length=200),
        ),
    ]
