# Generated by Django 5.2.4 on 2025-09-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_alter_product_add_vendor_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_add',
            name='vendor_product_brand',
            field=models.CharField(max_length=200),
        ),
    ]
