# Generated by Django 5.2.4 on 2025-09-26 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_alter_product_add_vendor_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_add',
            name='created_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
