# Generated by Django 5.2.4 on 2025-09-26 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_product_add_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_add',
            name='uploaded_at',
        ),
    ]
