# Generated by Django 5.2.4 on 2025-09-26 02:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0014_remove_product_add_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_add',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
