# Generated by Django 5.2.4 on 2025-09-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_product_add_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_add',
            name='uploaded_at',
        ),
    ]
