# Generated by Django 5.2.4 on 2025-09-30 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0021_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
