# Generated by Django 5.2.4 on 2025-09-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0023_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecomuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
