# Generated by Django 5.2.4 on 2025-09-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0024_ecomuser_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomuser',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
