# Generated by Django 5.2.4 on 2025-10-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0025_alter_ecomuser_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('standard', models.IntegerField(max_length=100)),
                ('doj', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.DeleteModel(
            name='ecomuser',
        ),
    ]
